services:
  app-proxy:
    container_name: proxy
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '5000:5000'
    depends_on:
      - app-client
      - app
    networks:
      - net

  app-client:
    container_name: client
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    networks:
      - net

  app:
    build: 
      context: ./backend
    container_name: news
    command: ['/app/docker/app.sh']
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - net

  db:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - 8123:8123
    networks:
      - net


volumes:
  clickhouse_data:

networks:
  net: